# Generated by Django 4.0.6 on 2023-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_countinstocks_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payementMethod',
            new_name='paymentMethod',
        ),
    ]
